func Fantasy()-> String {
    let randomNum = Int.random(in: 0..<3)
        print("Give an adjective")
        let adj1 = readLine()
        print("Give a name")
        let name = readLine()
        print("Give an activity")
        let activity1 = readLine()
        print("Give another activity")
        let activity2 = readLine()
        print("Give a third acivity")
        let activity3 = readLine()
        print("Give a past tense verb")
        let pastTenseVerb = readLine()
        print("Give an adjective")
        let adj2 = readLine()
        print("Give a female name")
        let femaleName = readLine()
        print("Give a verb/action")
        let action = readLine()
        print("Give an emotion")
        let emotion = readLine()
        print("Give the name of an animal")
        let animal = readLine()
        print("Give the name of a place")
        let place = readLine()
        print("Give the name of a game")
        let game = readLine()
        print("Give a quality or tool")
        let qualityOrTool = readLine()
        print("Give an adjective")
        let adj3 = readLine()
        print("Give a tool")
        let tool = readLine()
        print("Give the name of a title")
        let title = readLine()
        print("Give a country name")
        let country = readLine()
        print("Give the name of a gift")
        let gift = readLine()
        return ("Once there was a \(adj1 ?? "") knight named \(name ?? ""). He loved to \(activity1 ?? ""), \(activity2 ?? ""), and \(activity3 ?? ""). One day the king was \(pastTenseVerb ?? "") by a dragon. The dragon then kidnapped the \(adj2 ?? "") princess \(femaleName ?? ""). When the knight heard of this he \(action ?? "") in \(emotion ?? ""). He then rushed to his \(animal ?? "") and rode it to the place where the dragon lived: \(place ?? ""). When the knight arrived he challenged the dragon to a game of \(game ?? ""). The knight won using his \(qualityOrTool ?? ""). Victorious the knight rescued the \(adj3 ?? "") princess and held his \(tool ?? "") proudly in the air. The knight was named \(title ?? "") of the realm and was told in stories throughout \(country ?? ""). The princess, grateful, gave him a \(gift ?? "") as a thank you. The knight then happily for the rest of his life.")
}
func SciFi()-> String {
    let randomNum = Int.random(in: 0..<3)
    print("Give a noun")
    let noun = readLine()
    print("Give another noun")
    let noun2 = readLine()
    print("Give a place")
    let place = readLine()
    print("Give a plural noun")
    let pluralNoun = readLine()
    print("Give another plural noun")
    let pluralNoun2 = readLine()
    print("Give a singular noun")
    let noun3 = readLine()
    print("Give an adjective")
    let adj = readLine()
    print("Give a noun")
    let noun4 = readLine()
    print("Give a past-tense verb")
    let pastTenseVerb = readLine()
    print("Give a progressive verb")
    let progVerb = readLine()
    print("Give another progressive verb")
    let progVerb2 = readLine()
    print("Give a past-tense verb")
    let pastTenseVerb2 = readLine()
    print("Give a noun")
    let noun5 = readLine()
    return ("In the city of \(noun ?? ""), agent Z31, also known as agent \(noun2 ?? ""), was out getting supplies. For his trip to the farlands of \(place ?? ""), outside the city gates, he needed \(pluralNoun ?? ""), \(pluralNoun2 ?? ""), and the infamously rare \(noun3 ?? ""). As a recon agent, it is vital the agent Z31 is \(adj ?? ""). If the rival city, \(noun4 ?? "") City (noun), found out, he would instantly be \(pastTenseVerb ?? ""). Luckily, agent Z31 was one of the best, and soon after acquiring his materials, he headed out past the \(progVerb ?? "") guards. It wasn’t long before he reached the rival city. After \(progVerb2 ?? "") the electro-magnetic field gates, he \(pastTenseVerb2 ?? ""). Agent Z31 was in, and the fate of the \(noun5 ?? "") rested on his shoulders.")
}
func Mystery()-> String {
    let randomNum = Int.random(in: 0..<3)
    print("Give an adjective")
    let adj1 = readLine()
    print("Give an adjective")
    let adj2 = readLine()
    print("Give a noun")
    let noun1 = readLine()
    print("Give an adjective")
    let adj3 = readLine()
    print("Give an adjective")
    let adj4 = readLine()
    print("Give a progressive verb")
    let progVerb = readLine()
    print("Give an adjective")
    let adj5 = readLine()
    print("Give a city name")
    let cityName = readLine()
    print("Give an adjective")
    let adj6 = readLine()
    print("Give the name of a male")
    let maleName = readLine()
    print("Give an emotion")
    let emotion = readLine()
    print("Give a noun")
    let noun2 = readLine()
    print("Give a liquid")
    let liquid = readLine()
    print("Give a body part")
    let bodyPart = readLine()
    print("Give an adjective")
    let adj7 = readLine()
    print("Give a verb")
    let verb1 = readLine()
    print("Give a verb")
    let verb2 = readLine()
    print("Give an adjective")
    let adj8 = readLine()
    print("Give a verb")
    let verb3 = readLine()
    print("Give an adjective")
    let adj9 = readLine()
    return ("It was a(n)  \(adj1 ?? "") and  \(adj2 ?? "") night. A detective of \(noun1 ?? "") had just found himself upon a dead, \(adj3 ?? "") body and had to solve this \(adj4 ?? "") mystery. At first, he considered \(progVerb ?? "") the perimeter but noticed the \(adj5 ?? "") trail was cold. He went back to \(cityName ?? "") police station to report his \(adj6 ?? "") findings to Captain \(maleName ?? ""). The killer was yet to be found and the family of the victim were very \(emotion ?? ""). The clues of \(noun2 ?? "") weren’t adding up to the Captain \(maleName ?? ""). The fact that the \(liquid ?? "") spewing from the \(bodyPart ?? "") of the victim seemed to not match up with the \(adj7 ?? "") photos. He \(verb1 ?? "") after coming to an epiphany. The true culprit was the detective! He had \(verb2 ?? "") the details of the \(adj8 ?? "") death to cover up his crime. But before the detective could \(verb3 ?? ""), he suddenly lost his breath. He had been poisoned by the detective and his \(adj9 ?? "") life had come to an end.")
}
func Fable()-> String {
    print("Give a biome name")
    let biome = readLine()
    print("Give an adjective")
    let adj1 = readLine()
    print("Give an animal name")
    let animal = readLine()
    print("Give an action verb")
    let action1 = readLine()
    print("Give another action verb")
    let action2 = readLine()
    print("Give an adjective")
    let adj2 = readLine()
    print("Give an adjective")
    let adj3 = readLine()
    print("Give the name of a place")
    let namePlace = readLine()
    print("Give an action verb")
    let action3 = readLine()
    print("Give a plural noun")
    let pluralNoun = readLine()
    print("Give a noun")
    let noun = readLine()
    return ("In a \(biome ?? ""),  there lived a(n) \(adj1 ?? "") \(animal ?? "")  who lived happily. Then a fearsome lion entered the \(biome ?? "") and started \(action1 ?? "") and \(action2 ?? "") on the \(animal ?? ""). The \(animal ?? "") decided to take action against the \(adj2 ?? "") lion. With \(adj3 ?? "") skill the \(animal ?? "") trapped the lion in \(namePlace ?? ""). The \(animal ?? "") was able to \(action3 ?? "") in piece for the rest of its life. The \(pluralNoun ?? "") in the \(biome ?? "") now knew that strength doesn’t guarantee \(noun ?? "").")
}
func Superhero()-> String {
    print("Give a city name")
    let cityName = readLine()
    print("Give a color")
    let color1 = readLine()
    print("Give a noun")
    let noun1 = readLine()
    print("Give a time of the day")
    let time = readLine()
    print("Give the name of a bird")
    let bird = readLine()
    print("Give a talent or quality")
    let quality = readLine()
    print("Give a noun")
    let noun2 = readLine()
    print("Give a color")
    let color2 = readLine()
    print("Give an item or a family member")
    let item = readLine()
    print("Give an adverb")
    let adverb = readLine()
    print("Give a country name")
    let country = readLine()
    print("Give an adjective")
    let adj1 = readLine()
    print("Give a number")
    let number = readLine()
    print("Give a tv network")
    let tvNetwork = readLine()
    print("Give a country")
    let country2 = readLine()
    return ("In the city of \(cityName ?? ""), there was a superhero named \(color  ?? "") \(noun1 ?? "") who kept the city safe. This hero mostly operated during the \(time ?? "") and was often mistaken for a(n) \(bird ?? "").  The hero’s greatest strength was their \(quality ?? ""). The hero’s greatest nemesis was \(noun2 ?? "") \(color2 ?? ""). One day the nemesis stole the hero’s \(item ?? ""). The hero \(adverb ?? "") charged into the villain's lair which was in \(country ?? ""). After a \(adj1 ?? "") battle that lasted \(number ?? "") hours, the hero was victorious. The hero then became world-renowned and got a tv show on \(tvNetwork ?? ""). The hero then retired to \(country2 ?? "") and lived a long life.")
}
func Country()-> String {
    print("Give a noun")
    let noun = readLine()
    print("Give an adjective")
    let adj1 = readLine()
    print("Give a name")
    let name1 = readLine()
    print("Give a title")
    let title = readLine()
    print("Give another name")
    let name2 = readLine()
    print("Give another title")
    let title2 = readLine()
    print("Give a plural noun")
    let pluralNoun = readLine()
    print("Give a noun")
    let noun2 = readLine()
    print("Give an activity")
    let activity = readLine()
    print("Give a past-tense verb")
    let pastVerb = readLine()
    return ("It was a hot, dry day in \(noun ?? "") Ranch. Tumbleweeds were rolling under the \(adj1 ?? "") sun. Off in the distance, two men were having a standoff. On the left, \(name1 ?? "") the \(title ?? ""). On the right, \(name2 ?? "") the \(title2 ?? ""). A crowd of \(pluralNoun ?? "") were watching off in the distance. But why were they facing off? Two days prior, \(name1 ?? "") knocked over \(name2 ?? "")’s (noun). They immediately engaged in a(n) \(activity ?? ""). Finally, the \(pluralNoun ?? "")) started chanting. “3, 2, 1!” Both of them turned around and \(pastVerb ?? "").")
}
func realisticFiction()-> String {
    print("Give an adjective")
    let adj1 = readLine()
    print("Give another adjective")
    let adj2 = readLine()
    print("Give a type of bird")
    let bird = readLine()
    print("Give a room in a house")
    let room = readLine()
    print("Give a verb")
    let verb = readLine()
    print("Give another verb")
    let verb2 = readLine()
    print("Give a relative's name")
    let relName = readLine()
    print("Give a noun")
    let noun = readLine()
    print("Give a liquid")
    let liquid = readLine()
    print("Give a verb ending in -ing")
    let progVerb = readLine()
    print("Give a plural body part")
    let bodyPart = readLine()
    print("Give a plural noun")
    let pluralNoun = readLine()
    print("Give another verb ending in -ing")
    let progVerb2 = readLine()
    print("Give another noun")
    let noun2 = readLine()
    return ("It was a \(adj1 ?? ""), cold November day. I woke up to the \(adj2 ?? "") smell of \(bird ?? "") roasting in the \(room ?? "") downstairs. I \(verb ?? "") down the stairs to see if I could help \(verb2 ?? "") the dinner. “See if \(relName ?? "") needs a fresh \(noun ?? "").” So I carried a tray of glasses full of \(liquid ?? "") into the \(progVerb ?? "") room. When I got there, I couldn’t believe my \(bodyPart ?? "")! There were \(pluralNoun ?? "") \(progVerb2 ?? "") on the \(noun2 ?? "")!")
}
var userInput = ""
while userInput != "stop" {
    print("Hello player, are you ready to play MadLibs? \n First, you should pick what genre of MadLibs you want to play! \n There are 4 options: Fantasy, Sci-Fi, Mystery, or Fable, Pick one! If you're feeling lucky, then type random.") 
let genre = readLine()
if genre == "Fantasy" {
    print(Fantasy())
}
else if genre == "Sci-Fi" {
    print(SciFi())
}
else if genre == "Mystery" {
    print(Mystery())
}
else if genre == "Fable" {
    print(Fable())
}
else if genre == "Superhero" {
    print(Superhero())
}
else if genre == "Realistic Fiction" {
    print(realisticFiction())
}
else if genre == "random" {
    let randomInt = Int.random(in: 0..<6)
    if randomInt == 0 {
        print(Fantasy())
    }
    else if randomInt == 1 {
        print(SciFi())
    }
    else if randomInt == 2 {
        print(Mystery())
    }
    else if randomInt == 3 {
        print(Fable())
    }
    else if randomInt == 4 {
        print(Superhero())
    }
    else if randomInt == 5 {
        print(realisticFiction())
    }
}
print("Would you like to play again? Type stop if you don't want to play again or type anything if you do want to play again.")
userInput = readLine() ?? ""
}

